export default [
    {
        img:'https://github.com/Kushaalrajiv/AirBNB_ReactJS/blob/master/src/images/image1.png?raw=true',
        rating: '5.0',
        lesson:"Life lessons with Katie Zaferes",
        reviews:6,
        price:'137',
        country:"Israel",
        openSpots: 0,
    },
    {
        img: 'https://github.com/Kushaalrajiv/AirBNB_ReactJS/blob/master/src/images/mountain.png?raw=true',
        rating: '4.5',
        lesson:"Learn Wedding Photography",
        reviews:2,
        price:'112',
        country:"Bali",
        openSpots: 0,
    },
    {
        img:'https://github.com/Kushaalrajiv/AirBNB_ReactJS/blob/master/src/images/wedding.png?raw=true',
        rating: '4.8',
        lesson:"Group Mountian Biking",
        reviews:2,
        price:'149',
        country:"Vietnam",
        openSpots: 8,
    },
    {
        img: 'https://github.com/Kushaalrajiv/AirBNB_ReactJS/blob/master/src/images/guitar.png?raw=true',
        rating: '4.9',
        lesson:"Guitar Lessons",
        reviews:7,
        price:'130',
        country:"USA",
        openSpots: 0,
    },
    {
        img: 'https://github.com/Kushaalrajiv/AirBNB_ReactJS/blob/master/src/images/sing.png?raw=true',
        rating: '4.6',
        lesson:"Singing Class",
        reviews:4,
        price:'110',
        country:"India",
        openSpots: 3,
    },
    {
        img: 'https://github.com/Kushaalrajiv/AirBNB_ReactJS/blob/master/src/images/dance.png?raw=true',
        rating: '4.7',
        lesson:"Dance Class",
        reviews:11,
        price:'170',
        country:"Austria",
        openSpots: 5,
    },
    {
        img:'https://github.com/Kushaalrajiv/AirBNB_ReactJS/blob/master/src/images/swim.png?raw=true',
        rating: '4.9',
        lesson:"Swimming Class",
        reviews:18,
        price:'160',
        country:"Netherlands",
        openSpots: 0,
    }
]